<table class="title_list" width="700" cellpadding="2" cellspacing="0" border="0">
	<tr>
		<td width="500">
			Settlement Activities<font class="module_sep">&nbsp;&raquo;&nbsp;</font>Settings<font class="module_sep">&nbsp;&raquo;&nbsp;</font>User Info
		</td>
		<td width="200">
			<table class="fieldtitle" align="right" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td>
						<font class="goto">
							<b>Go To</b>
						</font>
					</td>
					<td width="5">
					</td>
					<td>
						<select id="cbPages"  class="dropdown_sf" >
							<option value="0">User Info</option>
							<option >Bank Info</option>
						</select>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
