<table class="table_bg" width="350" height="100%" align="center" cellpadding="0" cellspacing="0" border="0">
	<tr>
		<td>
			<table class="table_bg" width="350" height="100%" align="center" cellpadding="0" cellspacing="0" border="0">
				<tr height="22">
					<td class="title_module" width="300">
						&nbsp;Settlement Activities<font class="module_sep">&nbsp;&raquo;&nbsp;</font>Settings
					</td>
					<td class="help_module" width="50" align="center">
						<font class="cursor" title="Click here to view help..."  >Help</font>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td class="border_left_bottom_right">
			<table class="table_bg" height="100%" align="center" cellpadding="0" cellspacing="0" border="0">
				<tr height="26">
					<td>
						<b>Go To</b><font class="userinfo">&nbsp;&raquo;&nbsp;</font>
					</td>
					<td width="5">
					</td>
					<td>
						<font class="boldlink" onclick="UDModule.PROJEX.showPage('../en/a_userinfo/userinfo.jsp')" onmouseover="UDModule.PROJEX.highlightSection (this,true)" onmouseout="UDModule.PROJEX.highlightSection (this,false)">
							User Info 
						</font>
					</td>
					<td width="5">
					</td>
					<td>
						<font class="seperator">|</font>
					</td>
					<td width="5">
					</td>
					<td>
						<font class="boldlink" onclick="UDModule.PROJEX.showPage('../en/b_bankinfo/bankinfo.jsp')" onmouseover="UDModule.PROJEX.highlightSection (this, true)" onmouseout="UDModule.PROJEX.highlightSection (this,false)">
							Bank Info
						</font>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
